#!/bin/bash

set -e

service cron start > /dev/null 2>&1

cd /usr/local

mkdir -p /var/log/maubot /data/plugins /data/trash /data/dbs

if [ ! -f /data/config.yaml ]; then
	cp example-config.yaml /data/config.yaml
	echo "Config file not found. Example config copied to /data/config.yaml"
	echo "Please modify the config file to your liking and restart the container."
	exit
fi

alembic -x config=/data/config.yaml upgrade head
maubot -c /data/config.yaml -b /usr/local/example-config.yaml

/bin/bash

